spring:
    profiles:
       active:
       - dev
--- 
server:
    profiles: 8201
spring:
    profiles: dev      
    application:
       name: microservicecloud-config-client
eureka:
    client:
       service-url:
         defaultZone: http://eureka-dev.com:7001/eureka/
--- 
server:
    profiles: 8200
spring:
    profiles: test     
    application:
       name: microservicecloud-config-client
eureka:
    client:
       service-url:
         defaultZone: http://eureka-test.com:7001/eureka/